# Numpy = Numerical Python

Es el módulo principal para la información científica. Proporciona potentes estructuras de datos, implementando matrices(incluso multidimensiones), funciones matemáticas de alto nivel para operar con ellas eficazmente, etc.

Ventajas de Numpy
* Requiere menor memoria(comparada con la listas en Python) 
* Mayor rapidez en tiempo de ejecución

In [1]:
import numpy as np

## 1.- Creación de arreglos (array) por filas
### 1.1.- De una fila

In [2]:
lista = [1,2,3,4,5,6,7] # creamos una lista con 7 elementos

In [3]:
arreglo = np.array(lista) # creamos un objeto de tipo arreglo a través de una lista previamente definida

In [4]:
lista #imprimimos el contenido de 'lista'

[1, 2, 3, 4, 5, 6, 7]

In [5]:
# Los arreglos son distintos a las listas, por eso imprimimos su tipo
print(type(arreglo))
print(type(lista))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
print('Contenido del arreglo: ',arreglo)
print('Tamaño del arreglo: ',arreglo.size)##tamaño del arreglo
print('Dimensióndel arreglo (dimensiones, numero de elementos)',arreglo.shape)#forma del arreglo
print('Dimensiones del arreglo: ',arreglo.ndim)##numero de dimensiones
print('Tipo de dato del arreglo: ', arreglo.dtype) ##tipo de dato del arreglo, puede ser int, complex, float, etc
print('\n')
# ¿Qué significa 'int64'?  Es la capacidad de almacenamiento ->Int16: 2 bytes; Int32 y int: 4 bytes->Int64 : 8 bytes

# arreglo complejo
arreglo_complejo=np.array([1+3j,5,8+7j], dtype= complex)
print('Contenido del arreglo de tipo complejo', arreglo_complejo)
print('Tipo de dato del arreglo complejo: ', arreglo_complejo.dtype)
print('\n')
# arreglo flotante
arreglo_flotante=np.array([1.9,5,8], dtype= float)
print('Contenido del arreglo de tipo complejo', arreglo_flotante)
print('Tipo de dato del arreglo complejo: ', arreglo_flotante.dtype)

Contenido del arreglo:  [1 2 3 4 5 6 7]
Tamaño del arreglo:  7
Dimensióndel arreglo (dimensiones, numero de elementos) (7,)
Dimensiones del arreglo:  1
Tipo de dato del arreglo:  int64


Contenido del arreglo de tipo complejo [1.+3.j 5.+0.j 8.+7.j]
Tipo de dato del arreglo complejo:  complex128


Contenido del arreglo de tipo complejo [1.9 5.  8. ]
Tipo de dato del arreglo complejo:  float64


### 1.2.- De dos o más filas

In [7]:
arreglo_bidimensional = np.array([[1,2,3],[4,5,6]])# creación de arreglos bidimensionales.Arreglo de 2x3
print('Arreglo bidimensional: \n',arreglo_bidimensional) # imprime este arreglo bidimensional
arreglo_tridimensional = np.array([[1,2,3],[4,5,5],[7,8,6]]) # creación de arreglo tridimensional. Arreglo de 3x3
print('Arreglo tridimensional:\n',arreglo_tridimensional) #imprime este arreglo tridimensional

Arreglo bidimensional: 
 [[1 2 3]
 [4 5 6]]
Arreglo tridimensional:
 [[1 2 3]
 [4 5 5]
 [7 8 6]]


In [8]:
arreglo_bidimensional.shape # dimensión y número de elementos del arreglo

(2, 3)

In [9]:
arreglo_tridimensional.shape # dimensión y número de elementos del arreglo

(3, 3)

### 1.3.- Métodos para crear arreglos

In [10]:
arre1 = list(range(15)) #forma de crear listas desde 0 hasta 15-1
print(arre1)

arre2 = list(range(0,15,2)) #forma de crear listas, desde 0 hasta 15-1 de 2 en 2.
print(arre2)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[0, 2, 4, 6, 8, 10, 12, 14]


In [11]:
arre4 =np.arange(11) #lista que va de 0 a 11-1
print(arre4)
arre3 = np.arange(0,11,2)# Forma de crear listas en Numpy
#Es lo mismo que guardarlo en una variable: arr1= np.arange(0,11,2)
print(arre3)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [12]:
np.linspace(0,20,5)##(inicio,fin,núemero de muestras)

array([ 0.,  5., 10., 15., 20.])

In [13]:
arr5 = np.arange(9) # arreglo del0 al 9-1
arr6 = arr5.reshape((3,3)) # reshape convierte un rango plano a distintas dimensiones
print(arr5)
print(arr6)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 2.- Arreglos de ceros

In [14]:
zeros = np.zeros(5) #agrreglo de 5 elementos iguales a cero
print(zeros)

[0. 0. 0. 0. 0.]


In [15]:
bi = np.zeros((5,3)) # Creación de arreglo que define 5 filas y 3 renglones (dimensiones, elementos) = (filas, columnas)
print(bi)
print(bi.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5, 3)


## 3.- Arreglo de unos

In [16]:
unos= np.ones(5) # Arreglo de 5 elementos iguales a unos
unos


array([1., 1., 1., 1., 1.])

In [17]:
matrizunos = np.ones((5,3)) # arreglo de unos en una matriz de 5 x3 (5 filas y 3 columnas)
matrizunos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 4.- Matriz vacía

In [18]:
vacia = np.empty([3,2])
vacia

array([[4.64892390e-310, 6.89941959e-310],
       [2.05833592e-312, 2.14321575e-312],
       [6.79038654e-313, 6.79038654e-313]])

## 5.- Arreglos con elementos aleatorios

In [19]:
aleatorios2 = np.random.random([3,2]) # matriz con 3 filas y 2 columnas con números aleatorios
aleat_uniformes = np.random.uniform(size=5) # arreglo de 5 elementos con números con distribución uniforme
print(aleatorios2)
print(aleat_uniformes)

[[0.43883565 0.12630877]
 [0.24700291 0.28077291]
 [0.30203131 0.13830476]]
[0.48699436 0.46118961 0.20193413 0.44601267 0.52345414]


## 6.- Acceder a elementos de un arreglo

In [20]:
arr = np.array([1,2,3,4,5]) # Accede al elemento número con índice 4. 
arr[4]

5

In [21]:
arre = np.array([[1,2],[3,4]]) # Accede al elemento de la fila 1 y posición 1. Recordar que tanto la filas como las columnas
#inician en 0
arre[[1],[1]]

array([4])

In [22]:
aleator = np.arange(9)
aleator[1:3] ###podemos hacer slicing , Acceder desde el índice 1 hasta el 3

array([1, 2])

In [23]:
aleator[[8,1,2]] ###regresa elementos en esa posición

array([8, 1, 2])

In [24]:
aleator[aleator < 5] ### regresa elementos menores a .5

array([0, 1, 2, 3, 4])

## 7.- Operaciones

### 7.1.- Suma

In [25]:
x = np.array([3,4,5,6])

y = np.array([2,1,2,1])

In [26]:
x+y # suma elemento por elemento. 3+ 2; 4+1; 5+2; etc


array([5, 5, 7, 7])

### 7.2.- Multiplicación

In [27]:
x*y # multiplicación uno a uno

array([ 6,  4, 10,  6])

In [28]:
x*2 ##multiplicación por un escalar

array([ 6,  8, 10, 12])

### 7.3.- Exponencial

In [29]:
x**3 ###exponenciación de los elementos de un arreglo

array([ 27,  64, 125, 216])

### 7.4 División

In [30]:
x/y

array([1.5, 4. , 2.5, 6. ])

### 7.5.- Constantes

In [31]:
np.pi ###constantes

3.141592653589793

In [32]:
np.cos(np.pi) ###Funciones matemáticas

-1.0

In [33]:
x = np.arange(0,2*np.pi,np.pi/2) ##(start,stop,step)

In [34]:
x

array([0.        , 1.57079633, 3.14159265, 4.71238898])

In [35]:
np.round(np.cos(x)) #(arreglo,decimales =0 ,out= None)
##Redondea el numero dado de decimales

array([ 1.,  0., -1., -0.])

## 8.-Cosas extras que se pueden realizar

In [36]:
arreglo1 = np.arange(9).reshape((3,3))

In [37]:
arreglo1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arreglo2 = np.ones(9).reshape(3,3)

In [39]:
arreglo2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
arreglo3 = np.array([[2,1,2],
                     [1,2,1],
                     [2,1,2]])

In [41]:
arreglo3

array([[2, 1, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [42]:
arreglo1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 9.- Operación de matrices

In [43]:
arreglo1.diagonal() # obtiene la diagonal de la matriz

array([0, 4, 8])

In [44]:
arreglo1.transpose() # Ontiene la transpuesta de la matrix

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [45]:
matriz = np.array([[3,3,3],
                [9,3,7],
                [6,5,3]])

In [46]:
np.linalg.det(matriz) # obtiene el determinante de la matriz

47.999999999999986

  ![imagen](img.png)

In [47]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x


array([2., 3.])

 ![nombrede la imágen](solucion.png)